common:
  logicClass: "logic.ScalpingDealingLogic"
  leverage: 1.0
  lossCutPercentage: 0.0
exchange:
  apiKey: ""
  secret: ""
logic:
  profitTakePercentage: 0.0
  spread: 0.0
  notifyInterval: 0.0
  directionJudgePercentage: 0.0
  countJudgeRatio: 0.0
  judgeSecond: 0.0
  closeSecond: 0.0
slack:
  incomingWebhook: ""
